### ISSUE TITLE
Failed to generate 'example.g.dart' file

### ISSUE THREAD

**Issue by Asad4132** [trevorwang/retrofit.dart#118]
**pubspec.yaml file:**

```
name: base_project
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  retrofit: any
  logger: any  #for logging purpose


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any


flutter:
  uses-material-design: true
```

**example.dart file:**
```
import 'package:json_annotation/json_annotation.dart';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';

part 'example.g.dart';

@RestApi(baseUrl: "https://5d42a6e2bc64f90014a56ca0.mockapi.io/api/v1/")
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @GET("/tasks")
  Future<List<Task>> getTasks();
}

@JsonSerializable()
class Task {
  String id;
  String name;
  String avatar;
  String createdAt;

  Task({this.id, this.name, this.avatar, this.createdAt});

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
  Map<String, dynamic> toJson() => _$TaskToJson(this);
}
```

**When i run generator**

> [INFO] Generating build script...
> [INFO] Generating build script completed, took 356ms
> 
> [INFO] Creating build script snapshot......
> [INFO] Creating build script snapshot... completed, took 8.0s
> 
> [SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
> This is likely caused by a misconfigured builder definition.
> [SEVERE] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/retrofit_generator-1.1.0/lib/src/generator.dart:700:39: Error: The method 'getDisplayString
> ' isn't defined for the class 'DartType'. - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartla
> ng.org/analyzer-0.36.4/lib/dart/element/type.dart').Try correcting the name to the name of an existing method, or defining a method named 'getDispl
> ayString'.      return refer(constant.typeValue.getDisplayString());                                      ^^^^^^^^^^^^^^^^
> pub finished with exit code 78
