### ISSUE TITLE
type 'String' is not a subtype of type 'Map<String, dynamic>'. Dio decodes correctly

### ISSUE THREAD

**Issue by qbait** [trevorwang/retrofit.dart#227]
**Describe the bug**
I'm trying to implement 
```
  final dio = Dio();
  final response = await dio.get("https://gist.githubusercontent.com/qbait/f7c74d3e47f37df8704efe9bca88ea1b/raw/e82208ad032af582871d552f5da5573a80f36def/resume.json");
  final resume = Resume.fromJson(json.decode(response.data));
```
using `Retrofit.dart`
My service looks like
```
@RestApi(baseUrl: 'https://gist.githubusercontent.com/')
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @GET('/qbait/f7c74d3e47f37df8704efe9bca88ea1b/raw/e82208ad032af582871d552f5da5573a80f36def/resume.json')
  @Headers(<String, dynamic>{
    'Content-Type' : 'application/json'
  })
  Future<Resume> getResume();
}
```
As you can see, I explicitly defined `'Content-Type' : 'application/json'`.

I'm calling it like
```
  final dio = Dio();
  final client = RestClient(dio);
  await client.getResume().then((value) => logger.i('$value'));
```

The code implemented with `Dio` works as expected, the code implemented with `Retrofit.dart` throws
`[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'Map<String, dynamic>'`

My `pubspec.yaml`

```
dependencies:
  ...
  retrofit: ^1.3.4
  dio: 3.0.9
  json_serializable: ^3.3.0

dev_dependencies:
  ...
  build_runner: ^1.7.3
  retrofit_generator: ^1.3.4
```
