### ISSUE TITLE
Appears that the result is not json Map, but a String

### ISSUE THREAD

**Issue by nzackoya** [trevorwang/retrofit.dart#276]
**Describe the bug**
```
These are my dependencies
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.1
  firebase_analytics: ^6.1.0

  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  url_launcher: ^5.7.10
  fl_chart: ^0.12.0
  retrofit: any
  logger: any  #for logging purpose
  json_annotation: any

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  json_serializable: any
  build_runner: any
```

This is how I initialize 
```
final dio = Dio();
    dio.options.headers["content-type"] = "application/json";
    final client = ApiClient(dio);
```

When I run the request I'm getting error
```
DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'Map<String, dynamic>'
#0      DioMixin.assureResponse (
```

So appears that the result is not json Map, but a String.
