### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by DevNico** [trevorwang/retrofit.dart#300]
Dart Null Safety is in beta and packages should start to be migrated. 

Migration guide: https://dart.dev/null-safety/migration-guide

**Comment by NicolaChimerapps** [comment]
I have something very basic working in my fork in v1 https://github.com/Chimerapps/retrofit.dart/tree/feature/nullabilitysafe

**Comment by higorlapacw** [comment]
Any updates on this?

**Comment by RootSoft** [comment]
Same question - any updates for Null Safety?

**Comment by WillowWisp** [comment]
This is required to be used with Flutter 2.0

**Comment by vance-liu** [comment]
any updates?

**Comment by wwwdata** [comment]
@NicolaChimerapps  do you intend to finish the migration and open a PR? Or who is currently willing to take over and work on this topic? 

@WillowWisp it is not strictly required to use null safety for flutter 2.0. Only if you want to opt into null safety then we need a null safe version of retrofit, because otherwise the generated code will not be null safe (and is also not excluded from null safety) and therefore compilation fails :D Which currently is my show stopper for a null safe migration.

**Comment by explodus** [comment]
@wwwdata yeah, i see the problem, that all dependencies have to be null-safety, but i don't think it is really a problem. if someone don't have the time to get it done for his own proj/package, why shouldn't he mark all nullable. the sdk is now fully enabled with null-safety, for small projects without any dependency it would be easy to use it, but if more packages it changes, the more dependencies you can use again

we need the small packages to get migrated first, build, source_gen, retrofit_gen... and so on

**Comment by wwwdata** [comment]
I guess it would make sense to have this on the v1 branch since this is the one that is currently released. If that is null safe it's all good for now. And later on, null safety can also be introduced to the breaking changes and brand new v2 version. As I see, v2 development has stalled a little (last commit from summer last year) and the active development on the master branch (v1) has commits and releases.

**Comment by NicolaChimerapps** [comment]
Can everyone that wants this to continue please help me test the implementation I have. For that you need to point your retrofit_generator to my github fork:
```yaml
retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: generator
```
And then update your build.yaml to include the nullsafety option:
```yaml
targets:
  $default:
    builders:
      retrofit_generator|retrofit:
        enabled: true
        options:
          nullsafety: true
```

You can report issues here if you like, I will try to work on this as much as I can, no promises though.

**Comment by SashaFarkas** [comment]
@trevorwang Is update to null safety going to happen? Are you still maintaining this package?

**Comment by wwwdata** [comment]
@NicolaChimerapps great work! I tested it and so far the only thing left that is complainingto me is this issue from json_serializable for generic argument factories :D https://github.com/google/json_serializable.dart/issues/803
But at least no noticeable errors from your branch to me. I guess it would make sense if you can also open a PR  here soon and we can collect reviews :) 
Thanks so much!

**Comment by NicolaChimerapps** [comment]
Ok, let me check if I need to do some cleanup before creating the PR and then submit it

**Comment by NicolaChimerapps** [comment]
#312 created

**Comment by explodus** [comment]
it's so cool to see how quickly it's evolving

**Comment by manle93** [comment]
Please update built_collection to 5.0.0 (null-safety) versions too, this thing make it compatible with another packages.

**Comment by NicolaChimerapps** [comment]
> Please update dependencies: built_collection to 5.0.0 (null-safety) versions too, this thing make it compatible with another packages.

Then we would have to rewrite it all to support nullsafety. Which may be too much work. I will investigate too see how much effort this would take. But that would preclude updating for people that did not upgrade to 2.12 yet

**Comment by NicolaChimerapps** [comment]
Quick update: the generator would not even be compatible with dio 4.x release, as they have breaking changes. This will not be an easy upgrade. Hang in there!

**Comment by pratikpparikh** [comment]
@NicolaChimerapps you can use the following fix while we wait for the merge.  This should address google/json_serializable.dart#803

json_serializable:
    git:
      url: https://github.com/pratikpparikh/json_serializable.dart
      path: json_serializable
      ref: 25dbffbfbf1457ba92cf45e7ea4afa249e759ee6

**Comment by NicolaChimerapps** [comment]
An update was made to the PR that enables full nullsafety support with Dio in nullsafety mode (dio 4). This now required dart 2.12 and will always generate nullsafety-safe code. 
Please be a very early alpha tester while I figure out how to fix the tests and examples etc

**Comment by woprandi** [comment]
I can take some time to test your work

**Comment by woprandi** [comment]
Apparently I'm unable to test your work because of the dependency to retrofit 1.3.4 which depends on dio 3.
I noticed your `dependencies_overrides` block but it seems ignored for me

**Comment by NicolaChimerapps** [comment]
Yes, this is something I noticed during development too, there is a nice
dependency loop that can't be fixed as far as I know. You should get the
repository locally on the correct branch and refence them by path instead
of git.

**Comment by HelloCore** [comment]
This works for me
```
dependency_overrides:
  retrofit:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: annotation
  retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: generator
```
