### ISSUE TITLE
[Question]Only @JsonSerializable part is not generated

### ISSUE THREAD

**Issue by takeru-sato-excite** [trevorwang/retrofit.dart#305]
Thanks for the great library.

I implemented it according to the sample, but only the `@JsonSerializable()` part is not generated.

I would like to know if there are any mistakes.

## Command
`$ fvm flutter pub run build_runner build --delete-conflicting-outputs`

## rest_client.dart
```
rest_client.dart

import 'package:json_annotation/json_annotation.dart';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';

part 'rest_client.g.dart';

@RestApi(baseUrl: "https://5d42a6e2bc64f90014a56ca0.mockapi.io/api/v1/")
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @GET("/tasks")
  Future<List<Task>> getTasks();
}

@JsonSerializable()
class Task {
  String id;
  String name;
  String avatar;
  String createdAt;

  Task({this.id, this.name, this.avatar, this.createdAt});

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
  Map<String, dynamic> toJson() => _$TaskToJson(this);
}

```

## rest_client.g.dart
```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'rest_client.dart';

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

class _RestClient implements RestClient {
  _RestClient(this._dio, {this.baseUrl}) {
    ArgumentError.checkNotNull(_dio, '_dio');
    baseUrl ??= 'https://5d42a6e2bc64f90014a56ca0.mockapi.io/api/v1/';
  }

  final Dio _dio;

  String baseUrl;

  @override
  Future<List<Task>> getTasks() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.request<List<dynamic>>('/tasks',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    var value = _result.data
        .map((dynamic i) => Task.fromJson(i as Map<String, dynamic>))
        .toList();
    return value;
  }
}

```

## pubspec.yaml
```
pubspec.yaml

name: app
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # architecture
  provider: ^4.3.2+3
  flutter_state_notifier: ^0.6.1
  freezed_annotation: ^0.12.0

  # image
  cached_network_image: ^2.5.0

  # network
  retrofit: ^1.3.4+1
  retrofit_generator: ^1.4.1+2

  # log
  logger: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  freezed: ^0.12.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

```
