### ISSUE TITLE
Error in retrofit generated file -- constructor Response.fromJson not defined

### ISSUE THREAD

**Issue by mohammad-melhem** [trevorwang/retrofit.dart#316]
I'm using retrofit in my flutter application and I'm using json_serialzable as well to generate model classes (I followed the steps in the Readme section). When I run flutter pub run build_runner build --> it successfully generates the part file for both retrofit service (by retrofit generator) and model that contains fromJson and toJson (I'm using json_annotation lib with json_serializable to generate fromJson and toJson as stated in the readme as well in the Task example). The problem is that the class generted by retrofit has an error that Response doesn't have the method fromJson. Here is a snippet from the generated file of a user service 

![image](https://user-images.githubusercontent.com/10730846/111324532-87a48800-8673-11eb-997e-cdd380bf4e7a.png)

and here are the dependencies in my pubspec.yaml:

```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^3.24.0
  flutter_custom_clippers: ^1.1.2
  font_awesome_flutter: ^8.11.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  google_sign_in: ^4.5.9
  chips_choice: ^2.0.1
  logging: ^0.11.4
  path_provider: ^1.6.27
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  retrofit: ^1.3.4+1
  dio: ^3.0.10
  json_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  retrofit_generator: ^1.3.7+5
  build_runner: ^1.10.0
  json_serializable: ^3.5.0
```

Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (12 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

Note: I've also tried to use 'any' instead of a certain version (even though no problem with pub get) but still the same result. Your help is much appreciated and thank you for the awesome library and great efforts in advance.
