### ISSUE TITLE
Not support nullable

### ISSUE THREAD

**Issue by vishal0910** [trevorwang/retrofit.dart#335]
I have used floor_generator and retrofit generator, we have getting below error

**retrofit_generator-2.0.0-beta3/lib/src/generator.dart:1048:33: Error: The argument type 'String?' can't be assigned t
o the parameter type 'String' because 'String?' is nullable and 'String' isn't.**

Below are the dependancies we have used...

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  retrofit: ^2.0.0-beta1
  logger: ^1.0.0
  dio: ^4.0.0
  built_value: ^8.0.4
  json_annotation: ^4.0.1
  path_provider: ^2.0.1
  flutter_archive: ^3.0.0
  lottie: ^1.0.1
  shared_preferences: ^2.0.5
  flutter_inappwebview: ^5.3.2
  floor: ^1.1.0
  flutter:
    sdk: flutter

dependency_overrides:
  code_builder: ^4.0.0
  build_config: ^1.0.0
  retrofit:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: annotation
      ref: master
dev_dependencies:
  floor_generator: ^1.1.0
  build_runner: ^2.0.0
  retrofit_generator: ^2.0.0-beta3
  json_serializable: ^4.1.0
  built_value_generator: ^8.0.4
  flutter_native_splash: ^1.1.8+4

**Comment by NicolaVerbeeck** [comment]
This is known, you need to use the dependency overrides for retrofit_generator on master branch too.

**Comment by vishal0910** [comment]
Thanks... It's working..

```
dependency_overrides:
  retrofit:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: annotation
      ref: master
  retrofit_generator:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: generator
      ref: master
```
