### ISSUE TITLE
Error running build_runner

### ISSUE THREAD

**Issue by aarjan** [trevorwang/retrofit.dart#345]
I am getting this error while running build_runner.

**[SEVERE] retrofit_generator:retrofit on lib/model/api/rest_client.dart:**
```
type 'ExpandIterable<InterfaceType, MethodElement>' is not a subtype of type 'Iterable<MethodElementImpl>' of 'iterable'
```

**This is a sample implementation**
```
import 'package:retrofit/http.dart';
import 'package:dio/dio.dart' hide Headers;

part 'rest_client.g.dart';

@RestApi(baseUrl: AppConst.BASE_URL)
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @POST('/auth/token')
  @Headers(<String, dynamic>{'Authorization': 'Basic ${AppConst.BASIC_TOKEN}'})
  Future<Auth> login(@Body() LoginCreds creds);
}
```

flutter --version

Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (11 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.1
  build_runner: ^2.0.4
  json_serializable: ^4.1.2
  very_good_analysis: ^2.0.3

  mockito: ^5.0.9
  retrofit_generator: ^2.0.0

dependency_overrides:
  analyzer: ^1.7.0
  meta: ^1.4.0
```

**Comment by StanevPrime** [comment]
I encountered the same issue.

**Comment by NicolaVerbeeck** [comment]
I am looking into it, but it seems it's the analyzer dependency override which is not supported

**Comment by parkgrrr** [comment]
I'm running into the same issues while upgrading to flutter 2.2, I have no dependency overrides.

**Comment by zmeid** [comment]
Same here and no dependency overrides.

**Comment by avinashk369** [comment]
is there any workaround for now as i am stuck here.

**Comment by Heewookji** [comment]
pubspec.lock

```lock
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.0" 
```

Seems to be a temporary fix, setting analyzer version with 1.5.0(then run pub get) solved my error for now

**Comment by NicolaVerbeeck** [comment]
There is a fix in PR (#346). You could use dependency_overrides to temporarily reference it until this is released:
```yaml
dependency_overrides:
  retrofit_generator:
    git:
      url: git@github.com:Chimerapps/retrofit.dart.git
      ref: 9f90296751984b359937c38563da5b19db5550f5
      path: generator
```

**Comment by avinashk369** [comment]
> There is a fix in PR (#346). You could use dependency_overrides to temporarily reference it until this is released:
> 
> ```yaml
> dependency_overrides:
>   retrofit_generator:
>     git:
>       url: git@github.com:Chimerapps/retrofit.dart.git
>       ref: 9f90296751984b359937c38563da5b19db5550f5
>       path: generator
> ```

Git error. Command: `git clone --mirror git@github.com:Chimerapps/retrofit.dart.git /Users/avinashdhiraj/.pub-cache/git/cache/retrofit.dart-97e0ea9bd7b73614469715072089604bcaf23001`
stdout: 
stderr: Cloning into bare repository '/Users/avinashdhiraj/.pub-cache/git/cache/retrofit.dart-97e0ea9bd7b73614469715072089604bcaf23001'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

getting this error message

**Comment by g123k** [comment]
@avinashk369 Use the https instead:

```
  retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart.git
      ref: 9f90296751984b359937c38563da5b19db5550f5
      path: generator
```

**Comment by avinashk369** [comment]
> @avinashk369 Use https instead:
> 
> ```
>   retrofit_generator:
>     git:
>       url: https://github.com/Chimerapps/retrofit.dart.git
>       ref: 9f90296751984b359937c38563da5b19db5550f5
>       path: generator
> ```

much thanks :)

**Comment by maelfosso** [comment]
> git:
>       url: https://github.com/Chimerapps/retrofit.dart.git
>       ref: 9f90296751984b359937c38563da5b19db5550f5
>       path: generator

It's working like a 

> @avinashk369 Use https instead:
> 
> ```
>   retrofit_generator:
>     git:
>       url: https://github.com/Chimerapps/retrofit.dart.git
>       ref: 9f90296751984b359937c38563da5b19db5550f5
>       path: generator
> ```

It's working like a charm

**Comment by andoutica** [comment]
> There is a fix in PR (#346). You could use dependency_overrides to temporarily reference it until this is released:
> 
> ```yaml
> dependency_overrides:
>   retrofit_generator:
>     git:
>       url: git@github.com:Chimerapps/retrofit.dart.git
>       ref: 9f90296751984b359937c38563da5b19db5550f5
>       path: generator
> ```

Hi @NicolaVerbeeck, I changed this PR but nothing happen, even the *.g files haven't generated after clean :(

**Comment by NicolaVerbeeck** [comment]
@trevorwang can you release an update to pub.dev?

**Comment by frameset** [comment]
Yes, please do!

**Comment by parmarravi** [comment]
whats the solution?

**Comment by NicolaVerbeeck** [comment]
Until @trevorwang releases a new version to pub.dev. Place the following block in your `dependency_overrides` section in the yaml file
```yaml
retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart.git
      ref: 9f90296751984b359937c38563da5b19db5550f5
      path: generator
```
