### ISSUE TITLE
Run build_runner error 'Iterable<MethodElementImpl>' of 'iterable'

### ISSUE THREAD

**Issue by sudi909** [trevorwang/retrofit.dart#350]
I want to create a api services using dio and build_runner. But when I run 

> flutter pub run build_runner 

on terminal I got this error

> [SEVERE] retrofit_generator:retrofit on lib/web_services/api_services.dart:
> 
> type 'ExpandIterable<InterfaceType, MethodElement>' is not a subtype of type 'Iterable' of 'iterable'

This is my api services code.

```
part 'api_services.g.dart';

@RestApi(baseUrl: Preferences.hrmsAPI)
abstract class RestClient {
  factory RestClient(Dio dio) = _RestClient;

  @FormUrlEncoded()
  @GET('config')
  Future<WrappedResponse> config();

  @FormUrlEncoded()
  @GET('profile')
  Future<WrappedResponse> profile(@Header('Authorization') String token);
}
```

* Dart SDK Version 2.13.0
* build_runner: ^2.0.4
* retrofit_generator: ^2.0.0
* dio: ^4.0.0
* Linux (Pop Os 2.04)

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  dependency_validator: ^3.1.0
  flutter_launcher_icons: ^0.9.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  retrofit_generator: ^2.0.0
```
