### ISSUE TITLE
Code generation will fail if you use the DioResponseType annotation.

### ISSUE THREAD

**Issue by azeek** [trevorwang/retrofit.dart#452]
1. Create a project through the latest version of the flutter sdk or do a pub upgrade.

2.  When I run the build runner with the following code, I get the following error:
```dart
import 'dart:typed_data';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';

part 'retrofit_service.g.dart';

@RestApi(baseUrl: 'https://xxxx.com/')
abstract class RetrofitService  {
  factory RetrofitService(Dio dio, {String baseUrl}) = _RetrofitService;

  @GET('xxxx/xxxxx')
  @FormUrlEncoded()
  @DioResponseType(ResponseType.bytes)
  Future<Uint8List?> downloadImage(String baseUrl);
}

```

```
[SEVERE] retrofit_generator:retrofit on lib/src/service/retrofit_service.dart (cached):
Bad state: No element

```

4.  If you delete DioResponseType, code generation is successful.

pub yaml 
```yaml
dependencies:
  retrofit: ^3.0.1
  logger: any  #for logging purpose
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  dio_http2_adapter: ^2.0.0
  dio_smart_retry: ^1.1.0
  
dev_dependencies:
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.0
  json_serializable: ^6.1.4
```
