### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by cdprete** [trevorwang/retrofit.dart#460]
Hi.
I've defined a call as 
```dart
@MultiPart()
  @PUT('$singleContactUrl/images')
  Future<void> uploadContactImage({
    @Path() required String id,
    @Part(name: 'image') required List<int> image,
  });
```

which leads to the generated code:
```dart
  @override
  Future<void> uploadContactImage({required id, required image}) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _data = FormData();
    _data.files.add(MapEntry(
        'image',
        MultipartFile.fromBytes(
          image,
          filename: null,
        )));
    await _dio.fetch<void>(_setStreamType<void>(Options(
            method: 'PUT',
            headers: _headers,
            extra: _extra,
            contentType: 'multipart/form-data')
        .compose(_dio.options, 'phone-book/v1/contacts/${id}/images',
            queryParameters: queryParameters, data: _data)
        .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
    return null;
  }

  RequestOptions _setStreamType<T>(RequestOptions requestOptions) {
    if (T != dynamic &&
        !(requestOptions.responseType == ResponseType.bytes ||
            requestOptions.responseType == ResponseType.stream)) {
      if (T == String) {
        requestOptions.responseType = ResponseType.plain;
      } else {
        requestOptions.responseType = ResponseType.json;
      }
    }
    return requestOptions;
  }
```
and my Spring Boot backend complains with `MissingServletRequestPartException: Required request part 'image' is not present]`.

The `LogInterceptor` returns:
```
*** Request ***
uri: http://localhost:8080/phone-book/v1/contacts/a73c2cad-0634-4d4f-b91d-0cb8c64ad119/images
method: PUT
responseType: ResponseType.json
followRedirects: true
connectTimeout: 0
sendTimeout: 0
receiveTimeout: 0
receiveDataWhenStatusError: true
extra: {}
headers:
 content-type: multipart/form-data
data:
Instance of 'FormData'

*** DioError ***:
uri: http://localhost:8080/phone-book/v1/contacts/a73c2cad-0634-4d4f-b91d-0cb8c64ad119/images
DioError [DioErrorType.response]: Http status error [400]
uri: http://localhost:8080/phone-book/v1/contacts/a73c2cad-0634-4d4f-b91d-0cb8c64ad119/images
statusCode: 400
headers:
 access-control-allow-origin: *
 access-control-expose-headers: *
 cache-control: no-cache
	 no-store
	 max-age=0
	 must-revalidate
 content-type: application/json
 date: Thu
	 17 Mar 2022 20:13:21 GMT
 expires: 0
 pragma: no-cache
 referrer-policy: no-referrer
 transfer-encoding: chunked
 vary: Origin
	 Access-Control-Request-Method
	 Access-Control-Request-Headers
 x-content-type-options: nosniff
 x-frame-options: DENY
 x-xss-protection: 1 ; mode=block
Response Text:
... JSON with full stacktrace ...
```

Libraries:
```yaml
retrofit: ^3.0.1+1 # dependency
retrofit_generator: ^4.0.1 # dev dependency
build_runner: ^2.1.8 # dev dependency
```

Flutter doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale it-CH)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

I've tried with the Windows build as well as the Web build. How can this be fixed?
