### ISSUE TITLE
handle Enum in response and request

### ISSUE THREAD

**Issue by billyandco** [trevorwang/retrofit.dart#559]
While using swager_parse library to generate retrofit from swagger
there's some case where enum can be use in queryParameter
and some case where enum can be used for response but will need a fromJson method on enum

you will check in this pull request that we tried to find a way to deal with it
but when json is a String and generator try to cast as Map<String, dynamic>, it can be broken
we made a solution for toJson on enum, but i think it can be handle inside retrofit generator

https://github.com/Carapacik/swagger_parser/pull/18

**Comment by knyghtryda** [comment]
I'm currently running into this as well.  The workaround is to create an extension on the enum for the `toJson()`, but this ideally should be handled by retrofit directly.

**Comment by sooxt98** [comment]
this is solved all together with configuration below

```yaml
# pubspec.yaml
swagger_parser:
  enums_to_json: true

# build.yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
```

https://github.com/trevorwang/retrofit.dart/pull/596
https://github.com/rrousselGit/freezed/issues/86
