### ISSUE TITLE
In build_runner ^2.4.4 toJson() is not generated

### ISSUE THREAD

**Issue by Carapacik** [trevorwang/retrofit.dart#570]
I use freezed and json_serializable to generate DTO. And when generating with a new build_runner, this writes to me:
```
MyDto must provide a `toJson()` method which return a Map.
It is programmer's responsibility to make sure the RequestBodyDto is properly serialized
```
![image](https://github.com/trevorwang/retrofit.dart/assets/52125833/f780cc11-91e1-4297-b0f6-40c0053f8a0a)
I suppose after update this is because it's not worth runs_before for freezed and json_serializable in build.yaml.

[freezed](https://github.com/rrousselGit/freezed/blob/master/packages/freezed/build.yaml) starts generation before json_serializable, and json_serializable **should** start generation before retrofit:
1. freezed
2. json_serializable
3. retrofit

We need to somehow add a queue for generation

**Comment by Carapacik** [comment]
Like so
```yaml
builders:
  retrofit:
    target: ":retrofit"
    import: "package:retrofit_generator/retrofit_generator.dart"
    builder_factories: ["retrofitBuilder"]
    build_extensions: { ".dart": [".retrofit.g.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - "json_serializable|json_serializable"
      - "freezed|freezed"
```
