### ISSUE TITLE
Code generation is not working.

### ISSUE THREAD

**Issue by DevarshRanpara** [trevorwang/retrofit.dart#572]
**Describe the bug**
I am migrating my flutter project from flutter 2.0.0 to stable version, I have recentely updated all the flutter packages and retrofit is one of them. After updating packages I am unable to generate files in retrofit and I am facing same error everytime. I am facing same error as #250 

**To Reproduce**
Go to terminal and type following command
`flutter pub run build_runner build --delete-conflicting-outputs`

**Expected behavior**
It should generate files.

**Screenshots**
<img width="1083" alt="Screenshot 2023-05-18 at 1 43 41 PM" src="https://github.com/trevorwang/retrofit.dart/assets/26064415/83e08b33-bff5-45e7-9d29-a14da27617c8">

**Desktop (please complete the following information):**
M2 MacBook air version (13.3.1 (a) (22E772610a))

**Smartphone (please complete the following information):**
Android pixel 6 emulator

Error log file 
[error.log](https://github.com/trevorwang/retrofit.dart/files/11505861/error.log)

pubspec.yaml file.
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher:
  intl: ^0.18.1
  flutter_svg: 0.21.0
  cupertino_icons: 0.1.3
  path_provider: ^2.0.15
  spider: 4.2.0
  provider: 6.0.5
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  retrofit: 4.0.1
  logger: any
  get_it: 7.6.0
  sticky_headers: ^0.3.0+2
  flutter_conditional_rendering: 2.0.0
  pin_code_fields: 7.4.0
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  connectivity: 3.0.6
  file_picker: ^5.3.0
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  event_bus: 2.0.0
  flutter_linkify: ^6.0.0
  quiver: ^3.2.1
  mobx_codegen: ^2.3.0
  retrofit_generator: 5.0.0+1
  build_runner: '>=2.3.0 <4.0.0'

dependency_overrides:
  analyzer: 5.12.0
```
