### ISSUE TITLE
Code generation command not working

### ISSUE THREAD

**Issue by julianfalcionelli** [trevorwang/retrofit.dart#576]
**Describe the bug**
The latest version of retrofit_generator doesn't work, or at least doesn't work with the latest version of Flutter (3.10.+)

**To Reproduce**
Just run `dart run build_runner build --delete-conflicting-outputs`

**Screenshots**
<img width="1612" alt="Screen Shot 2023-05-24 at 12 14 04" src="https://github.com/trevorwang/retrofit.dart/assets/5782994/1326850a-527f-4191-a5cf-4dbc12bd4d33">

Even if I remove the file that is mentioned in `lib/ui/design/dropdown/app_dropdown_option.retrofit.g.part` some other random file takes its place. Not sure why `retrofit` is trying to generate a file from that class that doesn't have any reference for file generation, it's a normal Widget.

**Dev Dependencies**
```
dev_dependencies:
  # Flutter Code Styling Checker
  flutter_lints: ^2.0.1

  # Code Generation
  build_runner: ^2.4.4
  built_value_generator: ^8.6.0

  # Networking generation
  retrofit_generator: '>=7.0.0 <8.0.0'

  # Immutable models
  freezed: ^2.3.4

  # JSON serializer
  json_serializable: ^6.7.0

  # Assets generation
  assets_gen: ^1.5.0
```
