### ISSUE TITLE
Empty request body option is not working

### ISSUE THREAD

**Issue by behnamsattar** [trevorwang/retrofit.dart#614]
Before (on version 6.0.0) when I had the following build options:

```
targets:
  $default:
    builders:
      retrofit_generator|retrofit:
        options:
          empty_request_body: true
```

I would get empty request body objects instead of null objects. Resolving the issue I filed [here](https://github.com/trevorwang/retrofit.dart/issues/562).

On the newest version (7.0.8), this seems to be not working as I'm getting null data objects again in my code gen.
