### ISSUE TITLE
How to remove "baseUrl" in my ApiService.g to disable the hint

### ISSUE THREAD

**Issue by Naografix** [trevorwang/retrofit.dart#617]
Hello,

Not really an issue but I would like to know if it's possible to remove the baseUrl when I generate my API services. It's just because I would like to remove the blue hint, take a look:

![image](https://github.com/trevorwang/retrofit.dart/assets/6979203/e5a07477-6d93-4e48-9fc5-f9b03b1d25e2)

Thanks!

**Comment by jiechic** [comment]
Another solution I used
I added "*.g.dart" to the exclude of static analysis

**Comment by trevorwang** [comment]
As @jiechic  mentioned, add in your analysis_options.yaml file
```yaml
include: package:lints/recommended.yaml
analyzer:
  exclude:
    - lib/**/*.reflectable.dart
    - lib/**/*.g.dart
```
